name: Dummy Deploy Preview

on:
  workflow_run:
    workflows: ["Dummy Build Documentation"]
    types: [completed]

permissions:
  actions: read
  contents: read
jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Show triggering workflow information
        run: |
          echo "Run ID: ${{ github.event.workflow_run.id }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Original event: ${{ github.event.workflow_run.event }}"

      - name: Download PR number
        uses: actions/download-artifact@v5
        with:
          name: pr-number
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download documentation
        uses: actions/download-artifact@v5
        with:
          name: documentation
          path: downloaded-html
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read pr-number
        id: read-pr-number
        run: |
          PR_NUMBER=$(cat ./pr-number)
          echo "value=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Inspect downloaded artifacts
        run: |
          echo "PR number from step output:"
          echo "${{ steps.read-pr-number.outputs.value }}"
          
          echo "Downloaded documentation:"
          find downloaded-html -type f